/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.nemo.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.nemo.domain.Users;
import com.nemo.service.UserService;
import com.nemo.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-21-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm=(UserForm)form;
		/*调用service完成验证*/
		//1.创建并初始化一个User对象
		Users user=new Users();
		user.setName(userForm.getName());
		user.setPasswd(userForm.getPasswd());
		//2.创建service
		UserService userservice=new UserService();
		user=userservice.checkUser(user);
		if(user!=null){
			request.setAttribute("userinfo", user);
			return mapping.findForward("loginok");
		}else{ 
			return mapping.findForward("err");
		}
	}
}