/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.summer.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.summer.domin.Users;
import com.summer.service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GotoManagerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int pageSize=3;//每页的大小（记录数）
		/*获得要显示的页数*/
		int pageNow = 1;
		String pageNowStr=request.getParameter("pageNow");
		if(pageNowStr!=null){
			pageNow = Integer.parseInt(pageNowStr);
		}
		System.out.println("pageNow:"+pageNow);
		UserService us=new UserService();
		ArrayList  al=us.getUserByFenye(pageSize, pageNow);
		request.setAttribute("pageCount", us.getPageCount(pageSize));
		request.setAttribute("userspage",al );
		return mapping.findForward("gotoManager");
	}
}