/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.summer.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.summer.domin.Users;
import com.summer.service.UserService;
import com.summer.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2013
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		/*创建users这个domin对象*/
		Users users=new Users();
		users.setUser_id(userForm.getUser_id());
		users.setUser_pwd(userForm.getUser_pwd());
		/*创建service对象*/
		UserService us=new UserService();
		users=us.checkUser(users);
		if(users==null){
			//System.out.println("loginerr");
			return mapping.findForward("loginerr");
		}else{
			//System.out.println("loginok");
			request.getSession().setAttribute("userInfo", users);
			return mapping.findForward("loginok");
		}
	}
}