/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoli.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaoli.domain.Message;
import com.xiaoli.domain.Users;
import com.xiaoli.service.imp.MessageServiceImp;
import com.xiaoli.service.imp.UserServiceImp;
import com.xiaoli.service.inter.MessageServiceInter;
import com.xiaoli.service.inter.UserServiceInter;
import com.xiaoli.struts.form.MessageForm;
import com.xiaoli.utils.HibernateHelper;

public class GoPublishMessageUiAction extends DispatchAction {
	/*直接跳转到发布页面*/
	public ActionForward goPublishMessageUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goPublishMessageUi");
	}
	/*完成发送信息*/
	public ActionForward publishMessage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		MessageForm mf=(MessageForm)form;
		
		/*通过用户名字获取一个users对象*/
		UserServiceInter usi=new UserServiceImp();
		Users user=usi.getUsersByName(mf.getGetter());
		/*初始化message这个domain对象*/
		Message message=new Message();
		message.setContent(mf.getContent());
		message.setGetter(user);
		message.setMesTime(new Date());
		message.setSender((Users)request.getSession().getAttribute("userinfo"));
		
		/*保存message对象*/
		MessageServiceImp msi=new MessageServiceImp();
		msi.save(message);
		return mapping.findForward("ok");
	}
}