/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoli.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaoli.domain.Users;
import com.xiaoli.service.imp.UserServiceImp;
import com.xiaoli.service.inter.UserServiceInter;
import com.xiaoli.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-24-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserForm userForm=(UserForm)form;
		/*创建service对象*/
		
		/*用表单初始化一个domain对象*/
		Users user=new Users();
		user.setUser_id(Integer.parseInt(userForm.getUser_id()));
		user.setUser_passwd(userForm.getUser_passwd());
		/*调用service方法获得完整的domain对象*/
		
		/*通过接口来实现解耦*/
		UserServiceInter us=new UserServiceImp();
		user=us.checkUsers(user);
		System.out.println();
		
		if(user!=null){
			request.getSession().setAttribute("userinfo", user);
			return mapping.findForward("loginok");
		}else{
			return mapping.findForward("goLoginUi");
		}
		
	}
	/*
	 * 相应logout请求*/
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		/*清空session*/
		request.getSession().invalidate();
		return mapping.findForward("goLoginUi"); 
	}
}

