/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.web.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-15-2013
 * 
 * XDoclet definition:
 * @struts.action path="/reg" name="userForm" scope="request"
 */
public class RegAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		System.out.println(userForm.getUserid()+" "+userForm.getUsername()+" "+userForm.getEmail());
		/*
		 * 测试
		 * 1.创建service类
		 * 2.调用相关方法完成添加*/
		if(true){
			return mapping.findForward("ok");
		}else{
			return mapping.findForward("err");
		}
	}
}