/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.yourcompany.domin.RegisterInfo;
import com.yourcompany.service.RegistService;
import com.yourcompany.struts.form.UserForm;
import com.yourcompany.utils.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 07-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		String name=userForm.getName();
		FormFile formfile= userForm.getMyphoto();//取出用户上传的图片
		//通过formFile我们可以获取关于用户上传文件的各种信息
		//System.out.println(formfile.getFileName());
		//System.out.println(formfile.getFileSize());
		/*获得上传的原文件的文件名*/
		String filename=formfile.getFileName();
		/*获得不重复的新的文件名*/
		String filenameuuid=MyTools.getUUIDFileName(filename);
		InputStream  is=null;
		OutputStream os=null;
		RegistService rs=new RegistService();//service
		RegisterInfo ri=new RegisterInfo();//domin对象
		try {
			/*取出文件流*/
			is=formfile.getInputStream();
			/*得到一个输出流->文件
			 * 1.得到file文件夹上传到Tomcat服务器后的绝对路径*/
			String keepFilePath=this.getServlet().getServletContext().getRealPath("/files");
			/*2.构建输出流*/
			os=new FileOutputStream(keepFilePath+"\\"+filenameuuid);
			System.out.println(keepFilePath+"\\"+filename);
			/*3.读取文件并写出到服务器的file文件夹*/
			int len=0;
			//缓存读入
			byte[] b=new byte[1024];//创建一个1024bit大小的缓存区
			//循环读入
			while((len=is.read(b))>0){
				//读入缓存->冲缓存写入磁盘,循环进行知道read()返回-1，代表输出流已经到达末尾
				os.write(b,0,len);
			}
			/*4.如果用户上传ok我们把该用户的信息保存到数据库*/
	
			/*初始化domin对象*/
			ri.setName(name);
			ri.setPhoto(filename);
			ri.setPhotouuid(filenameuuid);
		
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			try {
				os.close();
				is.close();
			
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		if(rs.registerAdd(ri)){
			return mapping.findForward("registok");
		}else{
			return mapping.findForward("globalerr");
		}
	}
}